### ISSUE TITLE
Waterfall 1.18 - Bot hangs at "starting"

### ISSUE THREAD

**Issue by codingvincee** [OopsieWoopsie/Spicord#54] opened 2021-12-19 01:41 UTC
When completing the config and restarting the waterfall proxy, the bot doesn't get past the "Starting" phase. Same result when stopping the bot by command and starting again by command.

`
[02:29:37 INFO]: CONSOLE executed command: /sp status
[02:29:37 INFO]: [Spicord] > Status
[02:29:37 INFO]:  - BumbsAgent [Starting]
[02:29:37 INFO]: [Spicord] --------

sp stop BumbsAgent
[02:29:47 INFO]: CONSOLE executed command: /sp stop BumbsAgent
sp status
[02:29:55 INFO]: CONSOLE executed command: /sp status
[02:29:55 INFO]: [Spicord] > Status
[02:29:55 INFO]:  - BumbsAgent [Offline]
[02:29:55 INFO]: [Spicord] --------

sp start BumbsAgent
[02:30:03 INFO]: CONSOLE executed command: /sp start BumbsAgent
[02:30:03 INFO] [Spicord]: Starting bot 'BumbsAgent'.
[02:30:03 INFO]: The bot 'BumbsAgent' is being started
`

The bot token is correct in the config, double checked multiple times.

**Comment by ROKA611** [comment] 2021-12-19 13:02
Yes i have the same issue, i tried restarting the spicord by plugman even, after 10m or longer it is still [starting]

**Comment by OopsieWoopsie** [comment] 2021-12-20 15:03
> When completing the config and restarting the waterfall proxy, the bot doesn't get past the "Starting" phase. Same result when stopping the bot by command and starting again by command.
> 
> ` [02:29:37 INFO]: CONSOLE executed command: /sp status [02:29:37 INFO]: [Spicord] > Status [02:29:37 INFO]: - BumbsAgent [Starting] [02:29:37 INFO]: [Spicord] --------
> 
> sp stop BumbsAgent [02:29:47 INFO]: CONSOLE executed command: /sp stop BumbsAgent sp status [02:29:55 INFO]: CONSOLE executed command: /sp status [02:29:55 INFO]: [Spicord] > Status [02:29:55 INFO]: - BumbsAgent [Offline] [02:29:55 INFO]: [Spicord] --------
> 
> sp start BumbsAgent [02:30:03 INFO]: CONSOLE executed command: /sp start BumbsAgent [02:30:03 INFO] [Spicord]: Starting bot 'BumbsAgent'. [02:30:03 INFO]: The bot 'BumbsAgent' is being started `
> 
> The bot token is correct in the config, double checked multiple times.

Please send me your full server log.

**Comment by codingvincee** [comment] 2021-12-20 15:37
``> > When completing the config and restarting the waterfall proxy, the bot doesn't get past the "Starting" phase. Same result when stopping the bot by command and starting again by command.
> > ` [02:29:37 INFO]: CONSOLE executed command: /sp status [02:29:37 INFO]: [Spicord] > Status [02:29:37 INFO]: - BumbsAgent [Starting] [02:29:37 INFO]: [Spicord] --------
> > sp stop BumbsAgent [02:29:47 INFO]: CONSOLE executed command: /sp stop BumbsAgent sp status [02:29:55 INFO]: CONSOLE executed command: /sp status [02:29:55 INFO]: [Spicord] > Status [02:29:55 INFO]: - BumbsAgent [Offline] [02:29:55 INFO]: [Spicord] --------
> > sp start BumbsAgent [02:30:03 INFO]: CONSOLE executed command: /sp start BumbsAgent [02:30:03 INFO] [Spicord]: Starting bot 'BumbsAgent'. [02:30:03 INFO]: The bot 'BumbsAgent' is being started `
> > The bot token is correct in the config, double checked multiple times.
> 
> Please send me your full server log.

You can find the bot starting at [13:27:53]

[latest.log](https://github.com/Spicord/Spicord/files/7746348/latest.log)

**Comment by OopsieWoopsie** [comment] 2021-12-20 16:00
Please open the Spicord config and turn on the two options at the "jda_messages" section, and then send me the new log again.

By the way, I have tested Spicord 4.1.2 with the latest Waterfall release (1.18-R0.1-SNAPSHOT) and it worked without issue.

**Comment by codingvincee** [comment] 2021-12-20 19:45
jda messages were already enabled, enabled debug additionally and updated Waterfall to the latest available download. Here is the new logfile
[latest.log](https://github.com/Spicord/Spicord/files/7747622/latest.log)
:

**Comment by OopsieWoopsie** [comment] 2021-12-20 20:39
Are you using any other plugin that has some kind of "Discord Integration"?

**Comment by codingvincee** [comment] 2021-12-20 21:39
You triggered my curiousity and indeed, there seems to be a collision with UltraStaffChatPro. Is there any fix to have both plugins start a Discord Bot?

**Comment by codingvincee** [comment] 2021-12-20 22:00
Actually, it was my host -_-. Did some more testing and everything works just fine on my local machine running a hard copy of the proxy setup. Sorry to have waisted your time.

They have no clue how to resolve this, do you have any pointers I can give them?

**Comment by OopsieWoopsie** [comment] 2021-12-20 23:27
Hey, unfortunately I have no idea, but I have some theories;
As Discord uses CloudFlare for bot protection it can be because CloudFlare themselves have flagged the IP address or the whole IP subnet as suspicious.
Or maybe you are trying to run too many instances of your bot, for example by using the same token on 3+ different applications/plugins.

**Comment by OopsieWoopsie** [comment] 2021-12-28 16:26
Hi, are you using JDK17 (Java 17) ?

**Comment by OopsieWoopsie** [comment] 2021-12-28 17:05
Hello, I have updates on this issue :D
So, it turns out that Java 17 has a bug related to 1-core systems: https://bugs.openjdk.java.net/browse/JDK-8274349
Basically the bug was in this line of code (JDK code)
```java
    private ForkJoinPool(byte forCommonPoolOnly) {
        int parallelism = Runtime.getRuntime().availableProcessors() - 1; // <-- issue
```
If the availableProcessors() method returns 1 (as in 1-core systems), then the "- 1" part turns it to zero, that basically screws up everything.
The issue was fixed in this [pull request - click](https://togithub.com/openjdk/jdk/pull/5784)

I have managed to reproduce it with this setup:
- Paper 1.18.1
- Java 17 (Temurin)
- Limiting to 1-core using taskset

And managed to fix it by adding this JVM property:
`-Djava.util.concurrent.ForkJoinPool.common.parallelism=1`
Example use:
`java -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -jar server.jar`

So, it turned out that this wasn't a Spicord/Discord/CloudFlare issue, but a Java issue :upside_down_face: 

Btw, if you are running your server under a container (in the case of using pterodactyl panel then it does), then it very likely also is limited to 1-Core/vCore.
And it worked on your computer because your computer very likely doesn't has a single core cpu (hopefully).

**Closed as completed** 2022-01-04 02:19 UTC
