### ISSUE TITLE
Shutdown warning

### ISSUE THREAD

**Issue by DeriksonTM** [OopsieWoopsie/Spicord#47] opened 2021-10-10 10:39 UTC
When you turn off the server, often appears this varn https://pastebin.com/SBk20Zhi can you fix it?

**Comment by DeriksonTM** [comment] 2021-10-10 11:06
I'm use:

Purpur 1.16.5

**Comment by OopsieWoopsie** [comment] 2021-10-10 19:56
Hi, I had (and still have) this issue since I first moved Spicord to JDA 4 (it was later moved back to JDA 3).
I tried to fix it on 2 Sep 2020 ( https://github.com/Spicord/Spicord/commit/3d4ddac6b8f0a149b59853cc88c7283629793712 ) but I had no success, then tried it again the next day ( https://github.com/Spicord/Spicord/commit/3e5ab85bdffb7302e12ea8c80798848ec600bfe6 ) and from the commit title it seems like I fixed it, but I don't remember if it worked or not, none of those commits are currently part of Spicord, so the issue is still there, I will later (when I have some free time) apply the last mentioned fix to the current codebase to see if it fixes the issue.

You should not worry about it because it is nothing serious, just a warning saying there was a pending JDA task at that time.

**Comment by DeriksonTM** [comment] 2021-10-10 20:24
Okay, thank you very much, I will wait for the correction. ♥

**Comment by DeriksonTM** [comment] 2021-10-14 19:17
Sorry for the inconvenience. When is the update planned?

**Comment by OopsieWoopsie** [comment] 2021-10-15 00:43
Hello, I have made a build of the latest commit ( b01f08f )

(The .jar file is into this .zip file, I can't upload the .jar directly because GitHub restricts uplading .jar files)
[Spicord_build-b01f08f.zip](https://github.com/Spicord/Spicord/files/7350069/Spicord_build-b01f08f.zip)

Can you confirm if it works?
Note that the shutdown warning may or may not appear sometimes in the previous Spicord version (the one for which you reported the problem), so to be sure this new build fixes the issue it needs to be tested in long-term.

**Comment by DeriksonTM** [comment] 2021-10-16 19:55
Okay, I'm starting to test, if I get any errors, I'll let you know. If no errors are noticeable for 3 days, I will write to you. ♥

**Comment by DeriksonTM** [comment] 2021-10-16 19:59
look
[latest.log](https://github.com/Spicord/Spicord/files/7358189/latest.log)

**Comment by OopsieWoopsie** [comment] 2021-10-16 21:34
Oh :( It's not fixed... I will continue working on this when I have more free time

**Comment by DeriksonTM** [comment] 2021-11-03 18:20
Good day, and when approximately you will be able to solve the problem?

**Comment by OopsieWoopsie** [comment] 2021-11-03 19:01
Hello, there's no ETA yet, I need to try other ways of shutting down JDA without making it to trigger that warning, no idea when I will start doing that, I'm now more busier than before :( need to feed a baby bird in periods of 10-15 minutes for 12 hours each day. :bird:

**Comment by OopsieWoopsie** [comment] 2021-11-03 19:03
I will probably start doing it this night (in 4-5 hours from now) when the bird is sleeping

**Comment by DeriksonTM** [comment] 2021-11-04 08:01
Okay, thank you very much! It's just that I really care about this plugin and its proper operation for the server. I was just afraid that you wouldn't want to fix it :3 I'll wait for the update then. All the best to you! ♥

**Comment by OopsieWoopsie** [comment] 2021-11-04 15:16
Fixed by the fluffy friend!

![Image](https://i.imgur.com/PUyeBeM.jpg)

**Comment by OopsieWoopsie** [comment] 2021-11-04 15:18
Build of the latest commit: (.jar file is inside the .zip file)

[Spicord_4.1.0.zip](https://github.com/Spicord/Spicord/files/7475937/Spicord_4.1.0.zip)

**Comment by DeriksonTM** [comment] 2021-11-05 09:53
I'm going to try it now!
**UP:** Thank you so much! You have no idea how useful your plugin is to me!
Such a cute little bird :3 
I wish her good health, you and your loved ones! Thank you so much for all your work! ♥

**Closed as completed** 2021-11-05 09:53 UTC
